# Change these first
owner: rodseb # Your GitHub username
repo: Stats # Your Github repository name

# Add your sites here
sites:
  - name: "Site principal ROD Hosting"
    url: https://rod-hosting.com/
  - name: "Serveur Panel Web"
    url: https://panel.rod-hosting.com

  - name: "Serveur Linux Jeux" 
    url: $SECRET_SITE_3
## Serveur secondaire
  - name: "Serveur Secondaire (matomo)"
    url: $SECRET_SITE_4
 NOTIFICATION_EMAIL: true
 NOTIFICATION_EMAIL_FROM: Status service ROD Hosting
 NOTIFICATION_EMAIL_TO: $SECRET_SITE_5
 NOTIFICATION_EMAIL_SMTP: true
 NOTIFICATION_EMAIL_SMTP_PORT: 465
 NOTIFICATION_EMAIL_SMTP_HOST: rod-hosting.com
 NOTIFICATION_EMAIL_SMTP_USERNAME: $SECRET_SITE_6
 NOTIFICATION_EMAIL_SMTP_PASSWORD: $SECRET_SITE_7
 
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.rod-hosting.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
